### ISSUE TITLE
woeusb thinks "--target-filesystem NTFS" option is a full file system

### ISSUE THREAD

**Issue by ToddAndMargo** [WoeUSB/WoeUSB#95] opened 2021-12-02 22:49 UTC
Fedora 35
WoeUSB-5.1.2-3.fc35.x86_64

When you  use the "--target-filesystem NTFS" option, the option does what it is told, but them when woeusb does its thing it thinks the drive is full and there is no available space. This includes when you blank out the flash drive before issue th4e woeusb command.  After failure, you can verify with gparted that the last partition (the big one) is formatted NTFS and that the drive is full (partition wise)

```
> # dd bs=4096 if=/dev/zero of=/dev/sdc
> dd: error writing '/dev/sdc': No space left on device
> 1935361+0 records in
> 1935360+0 records out
> 7927234560 bytes (7.9 GB, 7.4 GiB) copied, 347.968 s, 22.8 MB/s
> 
> 
> # woeusb --target-filesystem NTFS --device Win11_21H2_English_x64.iso /dev/sdc
> WoeUSB v5.1.2
> ==============================
> Info: Mounting source filesystem...
> Info: Wiping all existing partition table and filesystem signatures in /dev/sdc...
> Info: Ensure that /dev/sdc is really wiped...
> Info: Creating new partition table on /dev/sdc...
> Info: Creating target partition...Info: Making system realize that partition table has changed...Info: Wait 3 seconds for block device nodes to populate...Cluster size has been automatically set to 4096 bytes.
> Creating NTFS volume structures.
> mkntfs completed successfully. Have a nice day.
> --2021-11-29 20:18:55-- https://github.com/pbatard/rufus/raw/master/res/uefi/uefi-ntfs.img
> Resolving github.com (github.com)... 140.82.114.3
> Connecting to github.com (github.com)|140.82.114.3|:443... connected.
> HTTP request sent, awaiting response... 302 Found
> Location: https://raw.githubusercontent.com/pbatard/rufus/master/res/uefi/uefi-ntfs.img [following]
> --2021-11-29 20:18:55-- https://raw.githubusercontent.com/pbatard/rufus/master/res/uefi/uefi-ntfs.img
> Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
> Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 1048576 (1.0M) [application/octet-stream]
> Saving to: ‘/tmp/WoeUSB.tempdir.RMyCvy/uefi-ntfs.img’
> 
> uefi-ntfs.img 100%[===============================================>]   1.00M   960KB/s    in 1.1s
> 
> 2021-11-29 20:18:57 (960 KB/s) - ‘/tmp/WoeUSB.tempdir.RMyCvy/uefi-ntfs.img’ saved [1048576/1048576]
> 
> dd: writing to '/dev/sdc2': No space left on device
> 1025+0 records in
> 1024+0 records out
> 524288 bytes (524 kB, 512 KiB) copied, 0.500646 s, 1.0 MB/s
> ERROR: The command "dd if="${download_directory}/uefi-ntfs.img" of="${uefi_ntfs_partition}"" failed with exit status "1", program is prematurely aborted
> Info: Unmounting and removing "/tmp/woeusb-source-20211129-201849-Monday.6IXKsM"...
> Info: Unmounting and removing "/tmp/woeusb-target-20211129-201849-Monday.zWqzA8"...
> umount: /tmp/woeusb-target-20211129-201849-Monday.zWqzA8: not mounted.
> Warning: Unable to unmount "/tmp/woeusb-target-20211129-201849-Monday.zWqzA8".
> Warning: Some mountpoints are not unmount/cleaned successfully and must be done manually
> Info: You may now safely detach the target device
> 

```

**Comment by brlin-tw** [comment] 2021-12-03 00:19
Duplicate of #81, please upgrade to 5.1.3.

**Closed as completed by brlin-tw** 2021-12-03 00:19 UTC
Labels: bug, duplicate

**Comment by ToddAndMargo** [comment] 2021-12-03 00:23
Thank you!  I asked downstream to upgrade to 5.1.3
