### ISSUE TITLE
dd: writing to '/dev/sdc2': No space left on device

### ISSUE THREAD

**Issue by jiriks74** [WoeUSB/WoeUSB#98] opened 2022-01-15 21:47 UTC
## Describe the bug ##
I'm trying to make a Windows 10 flashdisk (16GB), but everytime the program errors out after just few seconds.

## To Reproduce ##
1. Have clean 16GB USB stick with MBR partition table
2. Open `woeusbgui`
3. Select Windows 10 installation ISO
4. Select NTFS
5. Select the clean 16GB USB stick
6. Click install
7. Error pops up

## Error output: ##
<details>

```
Installation failed!
Exit code: 256
Log:
WoeUSB v3.3.1
==============================
Mounting source filesystem...
Wiping all existing partition table and filesystem signatures in /dev/sdc...
/dev/sdc: 2 bytes were erased at offset 0x000001fe (dos): 55 aa
/dev/sdc: calling ioctl to re-read partition table: Success
Ensure that /dev/sdc is really wiped...
Creating new partition table on /dev/sdc...
Creating target partition...
Making system realize that partition table has changed...
Wait 3 seconds for block device nodes to populate...
Cluster size has been automatically set to 4096 bytes.
Creating NTFS volume structures.
mkntfs completed successfully. Have a nice day.
--2022-01-15 22:39:29--  https://github.com/pbatard/rufus/raw/master/res/uefi/uefi-ntfs.img
SSL_INIT
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... pulse
connected.
HTTP request sent, awaiting response... pulse
302 Found
Location: https://raw.githubusercontent.com/pbatard/rufus/master/res/uefi/uefi-ntfs.img [following]
--2022-01-15 22:39:30--  https://raw.githubusercontent.com/pbatard/rufus/master/res/uefi/uefi-ntfs.img
SSL_INIT
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... pulse
connected.
HTTP request sent, awaiting response... pulse
200 OK
Length: 1048576 (1,0M) [application/octet-stream]
Saving to: ‘/tmp/WoeUSB.Q8ZZHY.tempdir/uefi-ntfs.img’
     0K .......... .......... .......... .......... ..........  4% 2,89M 0s
    50K .......... ...pulse
....... .......... .......... ..........  9% 2,23M 0s
   100K .......... .......... .......... .......... .......... 14% 3,65M 0s
   150K .......... .......... .......... .......... .......... 19% 18,3M 0s
   200K .......... .......... .......... .......... .......... 24%  450M 0s
   250K .......... .......... .......... .......... .......... 29% 3,74M 0s
   300K .......... .......... .......... .......... .......... 34% 2,48M 0s
   350K .......... .......... .......... .......... .........pulse
. 39% 6,56M 0s
   400K .......... .......... .......... .......... .......... 43% 4,27M 0s
   450K .......... .......... .......... .......... .......... 48% 3,37M 0s
   500K .......... .......... .......... .......... .......... 53% 3,35M 0s
   550K .......... .......... .....pulse
..... .......... .......... 58% 3,72M 0s
   600K .......... .......... .......... .......... .......... 63% 3,60M 0s
   650K .......... .......... .......... .......... .......... 68% 3,29M 0s
   700K .......... .......... .......... .......... .......... 73% 4,66M 0s
   750K .......pulse
... .......... .......... .......... .......... 78% 3,52M 0s
   800K .......... .......... .......... .......... .......... 83% 3,55M 0s
   850K .......... .......... .......... .......... .......... 87% 3,50M 0s
   900K .......... .......... ...pulse
....... .......... .......... 92% 1,80M 0s
   950K .......... .......... .......... .......... .......... 97% 9,55M 0s
  1000K .......... .......... ....                            100% 3,53M=0,3s
2022-01-15 22:39:30 (3,73 MB/s) - ‘/tmp/WoeUSB.Q8ZZHY.tempdir/uefi-ntfs.img’ saved [1048576/1048576]
dd: writing to '/dev/sdc2': No space left on device
1025+0 records in
1024+0 records out
524288 bytes (524 kB, 512 KiB) copied, 0,181633 s, 2,9 MB/s
The command "dd if="${download_directory}/uefi-ntfs.img" of="${uefi_ntfs_partition}"" failed with exit status "1", program is prematurely aborted
Unmounting and removing "/media/woeusb_source_1642282746_465960"...
You may now safely detach the target device
```

</details>

## Environment ##

- OS: Archlinux
- ZSH: `zsh 5.8 (x86_64-pc-linux-gnu)`
- (Bash: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`)
- WoeUSB: [e.g. 3.3.1]

**Comment by brlin-tw** [comment] 2022-01-15 21:58
Duplicate of #81, please upgrade to >=5.1.3.

**Closed as completed by brlin-tw** 2022-01-15 21:58 UTC
Labels: bug

**Comment by jiriks74** [comment] 2022-01-16 09:05
> Duplicate of #81, please upgrade to >=5.1.3.

Solved by installing `woeusb` not `woeusbgui` from AUR, compiling `WoeUSB-frontend-wxgtk` and running it without installing

**Comment by jiriks74** [comment] 2022-01-16 09:07
I don't understand code well yet, so would it be possible to have `WoeUSB` repository as a submodule in `WoeUSB-frontend-wxgtk` repository, so we could build `WoeUSB-frontend-wxgtk` with the newest version of `WoeUSB`?
